<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Currency;
use App\Models\Country; // Import Country model

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Cambodia Currency and Notes
        $cambodia = Country::where('slug', 'cambodia')->first();
        if ($cambodia) {
            $cambodia->currencies()->createMany([ // Use currencies() relationship
                // Banknotes
                ['denomination' => 50, 'year' => 2002, 'material' => 'Paper', 'is_active' => false, 'issue_date' => '2002-08-29', 'front_image_path' => 'img/Currencies/khmer riel/50_front.jpg', 'back_image_path' => 'img/Currencies/khmer riel/50_back.jpg', 'description' => 'Smallest denomination.', 'type' => 'Banknote'],
                ['denomination' => 100, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-12-27', 'front_image_path' => 'img/Currencies/khmer riel/100_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/100_back_v1.jpg', 'description' => 'Series from 2014.', 'type' => 'Banknote'],
                ['denomination' => 100, 'year' => 2001, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2001-08-09', 'front_image_path' => 'img/Currencies/khmer riel/100_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/100_back_v2.jpg', 'description' => 'Second version of 100 Riel.', 'type' => 'Banknote'],
                ['denomination' => 100, 'year' => 2015, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2015-01-14', 'front_image_path' => 'img/Currencies/khmer riel/100_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/100_back_v3.jpg', 'description' => 'Third version of 100 Riel.', 'type' => 'Banknote'],
                ['denomination' => 200, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-12-27', 'front_image_path' => 'img/Currencies/khmer riel/200_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/200_back_v1.jpg', 'description' => 'Newer series from 2022.', 'type' => 'Banknote'],
                ['denomination' => 200, 'year' => 2022, 'version' => 'v2', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '2022-11-14', 'front_image_path' => 'img/Currencies/khmer riel/200_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/200_back_v2.jpg', 'description' => 'Second version of 200 Riel.', 'type' => 'Banknote'],
                ['denomination' => 500, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-12-27', 'front_image_path' => 'img/Currencies/khmer riel/500_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/500_back_v1.jpg', 'description' => 'Widely circulated.', 'type' => 'Banknote'],
                ['denomination' => 500, 'year' => 2003, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2003-04-04', 'front_image_path' => 'img/Currencies/khmer riel/500_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/500_back_v2.jpg', 'description' => 'Second series, improved design.', 'type' => 'Banknote'],
                ['denomination' => 500, 'year' => 2015, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2015-01-14', 'front_image_path' => 'img/Currencies/khmer riel/500_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/500_back_v3.jpg', 'description' => 'Third version, added security features.', 'type' => 'Banknote'],
                ['denomination' => 1000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/1000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/1000_back_v1.jpg', 'description' => 'Standard 1000 Riel note.', 'type' => 'Banknote'],
                ['denomination' => 1000, 'year' => 1999, 'version' => 'v2', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1999-12-24', 'front_image_path' => 'img/Currencies/khmer riel/1000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/1000_back_v2.jpg', 'description' => 'Second version of 1000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 1000, 'year' => 2006, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2006-01-06', 'front_image_path' => 'img/Currencies/khmer riel/1000_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/1000_back_v3.jpg', 'description' => 'Third version of 1000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 1000, 'year' => 2013, 'version' => 'v4', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2013-01-29', 'front_image_path' => 'img/Currencies/khmer riel/1000_front_v4.jpg', 'back_image_path' => 'img/Currencies/khmer riel/1000_back_v4.jpg', 'description' => 'Fourth version of 1000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 1000, 'year' => 2017, 'version' => 'v5', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2017-10-25', 'front_image_path' => 'img/Currencies/khmer riel/1000_front_v5.jpg', 'back_image_path' => 'img/Currencies/khmer riel/1000_back_v5.jpg', 'description' => 'Fifth version of 1000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 2000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/2000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/2000_back_v1.jpg', 'description' => 'Standard 2000 Riel note.', 'type' => 'Banknote'],
                ['denomination' => 2000, 'year' => 2008, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/khmer riel/2000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/2000_back_v2.jpg', 'description' => 'Second version of 2000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 2000, 'year' => 2008, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2013-11-08', 'front_image_path' => 'img/Currencies/khmer riel/2000_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/2000_back_v3.jpg', 'description' => 'Third version of 2000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 2000, 'year' => 2022, 'version' => 'v4', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2022-11-14', 'front_image_path' => 'img/Currencies/khmer riel/2000_front_v4.jpg', 'back_image_path' => 'img/Currencies/khmer riel/2000_back_v4.jpg', 'description' => 'Fourth version of 2000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 5000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/5000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/5000_back_v1.jpg', 'description' => 'Standard 5000 Riel note.', 'type' => 'Banknote'],
                ['denomination' => 5000, 'year' => 2001, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2001-04-06', 'front_image_path' => 'img/Currencies/khmer riel/5000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/5000_back_v2.jpg', 'description' => 'Second version of 5000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 5000, 'year' => 2017, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2017-10-25', 'front_image_path' => 'img/Currencies/khmer riel/5000_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/5000_back_v3.jpg', 'description' => 'Third version of 5000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 10000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/10000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/10000_back_v1.jpg', 'description' => 'First version of 10,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 10000, 'year' => 2001, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2001-04-06', 'front_image_path' => 'img/Currencies/khmer riel/10000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/10000_back_v2.jpg', 'description' => 'Second version of 10,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 10000, 'year' => 2015, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2015-05-07', 'front_image_path' => 'img/Currencies/khmer riel/10000_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/10000_back_v3.jpg', 'description' => 'Third version of 10,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 15000, 'year' => 2019, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2019-10-07', 'front_image_path' => 'img/Currencies/khmer riel/15000_front.jpg', 'back_image_path' => 'img/Currencies/khmer riel/15000_back.jpg', 'description' => 'Commemorative banknote.', 'type' => 'Banknote'],
                ['denomination' => 20000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/20000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/20000_back_v1.jpg', 'description' => 'Common high denomination.', 'type' => 'Banknote'],
                ['denomination' => 20000, 'year' => 2008, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2008-05-12', 'front_image_path' => 'img/Currencies/khmer riel/20000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/20000_back_v2.jpg', 'description' => 'Second version of 20,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 20000, 'year' => 2018, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2018-05-16', 'front_image_path' => 'img/Currencies/khmer riel/20000_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/20000_back_v3.jpg', 'description' => 'Third version of 20,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 30000, 'year' => 2021, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2021-10-18', 'front_image_path' => 'img/Currencies/khmer riel/30000_front.jpg', 'back_image_path' => 'img/Currencies/khmer riel/30000_back.jpg', 'description' => 'New commemorative issue.', 'type' => 'Banknote'],
                ['denomination' => 50000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/50000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/50000_back_v1.jpg', 'description' => 'Highest active paper denomination.', 'type' => 'Banknote'],
                ['denomination' => 50000, 'year' => 2001, 'version' => 'v2', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '2001-04-06', 'front_image_path' => 'img/Currencies/khmer riel/50000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/50000_back_v2.jpg', 'description' => 'Second version of 50,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 50000, 'year' => 2014, 'version' => 'v3', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2014-05-06', 'front_image_path' => 'img/Currencies/khmer riel/50000_front_v3.jpg', 'back_image_path' => 'img/Currencies/khmer riel/50000_back_v3.jpg', 'description' => 'Third version with updated security.', 'type' => 'Banknote'],
                ['denomination' => 100000, 'year' => 1995, 'version' => 'v1', 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1995-03-25', 'front_image_path' => 'img/Currencies/khmer riel/100000_front_v1.jpg', 'back_image_path' => 'img/Currencies/khmer riel/100000_back_v1.jpg', 'description' => 'High value note.', 'type' => 'Banknote'],
                ['denomination' => 100000, 'year' => 2013, 'version' => 'v2', 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2013-04-30', 'front_image_path' => 'img/Currencies/khmer riel/100000_front_v2.jpg', 'back_image_path' => 'img/Currencies/khmer riel/100000_back_v2.jpg', 'description' => 'Second version of 100,000 Riel.', 'type' => 'Banknote'],
                ['denomination' => 200000, 'year' => 2024, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2024-10-16', 'front_image_path' => 'img/Currencies/khmer riel/200000_front.jpg', 'back_image_path' => 'img/Currencies/khmer riel/200000_back.jpg', 'description' => 'Newest and highest denomination.', 'type' => 'Banknote'],
                // Coins
                ['denomination' => 50, 'year' => 1994, 'material' => 'Steel', 'is_active' => false, 'issue_date' => '1994-01-01', 'front_image_path' => 'img/Currencies/khmer riel/50_riels_coin_obverse.jpg', 'back_image_path' => 'img/Currencies/khmer riel/50_riels_coin_reverse.jpg', 'description' => 'Coin: Not commonly used.', 'type' => 'Coin'],
                ['denomination' => 100, 'year' => 1994, 'material' => 'Steel', 'is_active' => false, 'issue_date' => '1994-01-01', 'front_image_path' => 'img/Currencies/khmer riel/100_riels_coin_obverse.jpg', 'back_image_path' => 'img/Currencies/khmer riel/100_riels_coin_reverse.jpg', 'description' => 'Coin: Not commonly used.', 'type' => 'Coin'],
                ['denomination' => 200, 'year' => 1994, 'material' => 'Steel', 'is_active' => false, 'issue_date' => '1994-01-01', 'front_image_path' => 'img/Currencies/khmer riel/200_riels_coin_obverse.jpg', 'back_image_path' => 'img/Currencies/khmer riel/200_riels_coin_reverse.jpg', 'description' => 'Coin: Not commonly used.', 'type' => 'Coin'],
                ['denomination' => 500, 'year' => 1994, 'material' => 'Bi-Metallic', 'is_active' => false, 'issue_date' => '1994-01-01', 'front_image_path' => 'img/Currencies/khmer riel/500_riels_coin_obverse.jpg', 'back_image_path' => 'img/Currencies/khmer riel/500_riels_coin_reverse.jpg', 'description' => 'Coin: Not commonly used.', 'type' => 'Coin']
            ]);
        }

        // China Currency and Notes
        $china = Country::where('slug', 'china')->first();
        if ($china) {
            $china->currencies()->createMany([
                ['denomination' => 1, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/1yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/1yuan_back.jpg', 'description' => 'Fifth series, green color.', 'type' => 'Banknote'],
                ['denomination' => 2, 'year' => 1999, 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1999-01-01', 'deactivated_end_date' => '2004-10-25', 'front_image_path' => 'img/Currencies/chinese yuan/2yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/2yuan_back.jpg', 'description' => 'Fifth series, discontinued.', 'type' => 'Banknote'],
                ['denomination' => 5, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/5yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/5yuan_back.jpg', 'description' => 'Fifth series, purple color.', 'type' => 'Banknote'],
                ['denomination' => 10, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/10yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/10yuan_back.jpg', 'description' => 'Fifth series, blue color.', 'type' => 'Banknote'],
                ['denomination' => 20, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/20yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/20yuan_back.jpg', 'description' => 'Fifth series, orange color.', 'type' => 'Banknote'],
                ['denomination' => 50, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/50yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/50yuan_back.jpg', 'description' => 'Fifth series, green/blue color.', 'type' => 'Banknote'],
                ['denomination' => 100, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/100yuan_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/100yuan_back.jpg', 'description' => 'Fifth series, red color, high value.', 'type' => 'Banknote'],
                ['denomination' => 1, 'year' => 2000, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/1jiao_coin_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/1jiao_coin_back.jpg', 'description' => 'Aluminum coin, part of 4th series.', 'type' => 'Coin'],
                ['denomination' => 5, 'year' => 2000, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/5jiao_coin_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/5jiao_coin_back.jpg', 'description' => 'Brass coin, part of 4th series.', 'type' => 'Coin'],
                ['denomination' => 1, 'year' => 2000, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/1yuan_coin_front.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/1yuan_coin_back.jpg', 'description' => 'Nickel-plated steel coin, part of 4th series.', 'type' => 'Coin'],
                ['denomination' => 1, 'year' => 1999, 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1999-01-01', 'deactivated_end_date' => '2015-11-12', 'front_image_path' => 'img/Currencies/chinese yuan/1jiao_note_back.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/1jiao_note_back.jpg', 'description' => 'Older 1 Jiao banknote.', 'type' => 'Banknote'],
                ['denomination' => 5, 'year' => 1999, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1999-01-01', 'front_image_path' => 'img/Currencies/chinese yuan/5jiao_note_back.jpg', 'back_image_path' => 'img/Currencies/chinese yuan/5jiao_note_back.jpg', 'description' => 'Older 5 Jiao banknote.', 'type' => 'Banknote'],
            ]);
        }

        // Vietnam Currency and Notes
        $vietnam = Country::where('slug', 'vietnam')->first();
        if ($vietnam) {
            $vietnam->currencies()->createMany([
                ['denomination' => 100, 'year' => 1991, 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1991-01-01', 'deactivated_end_date' => '2007-01-01', 'front_image_path' => 'img/Currencies/vietnamese dong/100_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/100_dong_back.jpg', 'description' => 'Cotton banknote.', 'type' => 'Banknote'],
                ['denomination' => 500, 'year' => 1989, 'material' => 'Paper', 'is_active' => false, 'issue_date' => '1989-01-01', 'deactivated_end_date' => '2007-01-01', 'front_image_path' => 'img/Currencies/vietnamese dong/500_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/500_dong_back.jpg', 'description' => 'Cotton banknote.', 'type' => 'Banknote'],
                ['denomination' => 1000, 'year' => 1988, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1988-01-01', 'front_image_path' => 'img/Currencies/vietnamese dong/1000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/1000_dong_back.jpg', 'description' => 'Cotton banknote.', 'type' => 'Banknote'],
                ['denomination' => 2000, 'year' => 1988, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1988-01-01', 'front_image_path' => 'img/Currencies/vietnamese dong/2000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/2000_dong_back.jpg', 'description' => 'Cotton banknote.', 'type' => 'Banknote'],
                ['denomination' => 5000, 'year' => 1991, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '1991-01-01', 'front_image_path' => 'img/Currencies/vietnamese dong/5000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/5000_dong_back.jpg', 'description' => 'Cotton banknote.', 'type' => 'Banknote'],
                ['denomination' => 10000, 'year' => 2003, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2003-12-17', 'front_image_path' => 'img/Currencies/vietnamese dong/10000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/10000_dong_back.jpg', 'description' => 'Polymer banknote, first issued in 2003.', 'type' => 'Banknote'],
                ['denomination' => 20000, 'year' => 2003, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2003-12-17', 'front_image_path' => 'img/Currencies/vietnamese dong/20000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/20000_dong_back.jpg', 'description' => 'Polymer banknote.', 'type' => 'Banknote'],
                ['denomination' => 50000, 'year' => 2003, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2003-12-17', 'front_image_path' => 'img/Currencies/vietnamese dong/50000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/50000_dong_back.jpg', 'description' => 'Polymer banknote.', 'type' => 'Banknote'],
                ['denomination' => 100000, 'year' => 2003, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2003-12-17', 'front_image_path' => 'img/Currencies/vietnamese dong/100000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/100000_dong_back.jpg', 'description' => 'Polymer banknote.', 'type' => 'Banknote'],
                ['denomination' => 200000, 'year' => 2006, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2006-08-30', 'front_image_path' => 'img/Currencies/vietnamese dong/200000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/200000_dong_back.jpg', 'description' => 'Polymer banknote.', 'type' => 'Banknote'],
                ['denomination' => 500000, 'year' => 2006, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2006-08-30', 'front_image_path' => 'img/Currencies/vietnamese dong/500000_dong_front.jpg', 'back_image_path' => 'img/Currencies/vietnamese dong/500000_dong_back.jpg', 'description' => 'Highest denomination polymer banknote.', 'type' => 'Banknote']
            ]);
        }


// Thailand Currency and Notes
$thailand = Country::where('slug', 'thailand')->first();
if ($thailand) {
    $thailand->currencies()->createMany([
        // Coins (These appear to be all present and correct)
        ['denomination' => 1, 'year' => 2008, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/thai baht/1_baht_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/1_baht_back.jpg', 'description' => 'Standard 1 Baht coin.', 'type' => 'Coin'],
        ['denomination' => 2, 'year' => 2008, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/thai baht/2_baht_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/2_baht_back.jpg', 'description' => 'Standard 2 Baht coin.', 'type' => 'Coin'],
        ['denomination' => 5, 'year' => 2008, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/thai baht/5_baht_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/5_baht_back.jpg', 'description' => 'Standard 5 Baht coin.', 'type' => 'Coin'],
        ['denomination' => 10, 'year' => 2008, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/thai baht/10_baht_coin_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/10_baht_coin_back.jpg', 'description' => 'Standard 10 Baht coin.', 'type' => 'Coin'],
        ['denomination' => 25, 'year' => 2008, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/thai baht/25_satang_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/25_satang_back.jpg', 'description' => 'Fractional coin.', 'type' => 'Coin'],
        ['denomination' => 50, 'year' => 2008, 'material' => 'Coin', 'is_active' => true, 'issue_date' => '2008-01-01', 'front_image_path' => 'img/Currencies/thai baht/50_satang_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/50_satang_back.jpg', 'description' => 'Fractional coin.', 'type' => 'Coin'],

        // Banknotes - 16th Series (These appear to be all present and correct)
        ['denomination' => 20, 'year' => 2013, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2013-04-24', 'series' => '16', 'front_image_path' => 'img/Currencies/thai baht/20_baht_16_front.png', 'back_image_path' => 'img/Currencies/thai baht/20_baht_16_back.png', 'description' => '16th Series, green.', 'type' => 'Banknote'],
        ['denomination' => 50, 'year' => 2012, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2012-01-18', 'series' => '16', 'front_image_path' => 'img/Currencies/thai baht/50_baht_16_front.png', 'back_image_path' => 'img/Currencies/thai baht/50_baht_16_back.png', 'description' => '16th Series, blue.', 'type' => 'Banknote'],
        ['denomination' => 100, 'year' => 2012, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2012-03-09', 'series' => '16', 'front_image_path' => 'img/Currencies/thai baht/100_baht_16_front.png', 'back_image_path' => 'img/Currencies/thai baht/100_baht_16_back.png', 'description' => '16th Series, red.', 'type' => 'Banknote'],
        ['denomination' => 500, 'year' => 2014, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2014-05-12', 'series' => '16', 'front_image_path' => 'img/Currencies/thai baht/500_baht_16_front.png', 'back_image_path' => 'img/Currencies/thai baht/500_baht_16_back.png', 'description' => '16th Series, purple.', 'type' => 'Banknote'],
        ['denomination' => 1000, 'year' => 2015, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2015-08-21', 'series' => '16', 'front_image_path' => 'img/Currencies/thai baht/1000_baht_16_front.png', 'back_image_path' => 'img/Currencies/thai baht/1000_baht_16_back.png', 'description' => '16th Series, brown.', 'type' => 'Banknote'],

        // Banknotes - 17th Series (Updated with missing notes)
        ['denomination' => 20, 'year' => 2018, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2018-03-24', 'series' => '17', 'front_image_path' => 'img/Currencies/thai baht/20_baht_17_front.jpg', 'back_image_path' => 'img/Currencies/thai baht/20_baht_17_back.jpg', 'description' => '17th Series, polymer, green.', 'type' => 'Banknote'],
        ['denomination' => 50, 'year' => 2018, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2018-03-24', 'series' => '17', 'front_image_path' => 'img/Currencies/thai baht/50_baht_17_front.png', 'back_image_path' => 'img/Currencies/thai baht/50_baht_17_back.png', 'description' => '17th Series, blue.', 'type' => 'Banknote'],
        // ADDED: 100 Baht, 17th Series
        ['denomination' => 100, 'year' => 2018, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2018-03-24', 'series' => '17', 'front_image_path' => 'img/Currencies/thai baht/100_baht_17_front.png', 'back_image_path' => 'img/Currencies/thai baht/100_baht_17_back.png', 'description' => '17th Series, red.', 'type' => 'Banknote'],
        // ADDED: 500 Baht, 17th Series
        ['denomination' => 500, 'year' => 2018, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2018-03-24', 'series' => '17', 'front_image_path' => 'img/Currencies/thai baht/500_baht_17_front.png', 'back_image_path' => 'img/Currencies/thai baht/500_baht_17_back.png', 'description' => '17th Series, purple.', 'type' => 'Banknote'],
        // ADDED: 1000 Baht, 17th Series
        ['denomination' => 1000, 'year' => 2018, 'material' => 'Polymer', 'is_active' => true, 'issue_date' => '2018-03-24', 'series' => '17', 'front_image_path' => 'img/Currencies/thai baht/1000_baht_17_front.png', 'back_image_path' => 'img/Currencies/thai baht/1000_baht_17_back.png', 'description' => '17th Series, brown.', 'type' => 'Banknote'],
    ]);
}

        // USA Currency and Notes - ADDED THIS SECTION
        $usa = Country::where('slug', 'usa')->first();
        if ($usa) {
            $usa->currencies()->createMany([
                // Example USD Banknotes
                ['denomination' => 1, 'year' => 2013, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2013-12-01', 'front_image_path' => 'img/Currencies/us dollar/1_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/1_back.jpg', 'description' => 'Federal Reserve Note.', 'type' => 'Banknote'],
                ['denomination' => 2, 'year' => 2003, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2003-01-01', 'front_image_path' => 'img/Currencies/us dollar/2_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/2_back.jpg', 'description' => 'Federal Reserve Note.', 'type' => 'Banknote'],
                ['denomination' => 5, 'year' => 2006, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2006-05-18', 'front_image_path' => 'img/Currencies/us dollar/5_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/5_back.jpg', 'description' => 'Federal Reserve Note.', 'type' => 'Banknote'],
                ['denomination' => 10, 'year' => 2006, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2006-03-02', 'front_image_path' => 'img/Currencies/us dollar/10_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/10_back.jpg', 'description' => 'Federal Reserve Note.', 'type' => 'Banknote'],
                ['denomination' => 20, 'year' => 2003, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2003-10-27', 'front_image_path' => 'img/Currencies/us dollar/20_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/20_back.jpg', 'description' => 'Federal Reserve Note.', 'type' => 'Banknote'],
                ['denomination' => 50, 'year' => 2004, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2004-09-28', 'front_image_path' => 'img/Currencies/us dollar/50_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/50_back.jpg', 'description' => 'Federal Reserve Note.', 'type' => 'Banknote'],
                ['denomination' => 100, 'year' => 2009, 'material' => 'Paper', 'is_active' => true, 'issue_date' => '2013-10-08', 'front_image_path' => 'img/Currencies/us dollar/100_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/100_back.jpg', 'description' => 'Federal Reserve Note, new design.', 'type' => 'Banknote'],
                // Example USD Coins
                ['denomination' => 1, 'year' => 2000, 'material' => 'Copper-plated Zinc', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/us dollar/1cent_penny_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/1cent_penny_back.jpg', 'description' => 'One cent coin (penny).', 'type' => 'Coin'],
                ['denomination' => 5, 'year' => 2000, 'material' => 'Copper-Nickel', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/us dollar/5cents_nickel_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/5cents_nickel_back.jpg', 'description' => 'Five cent coin (nickel).', 'type' => 'Coin'],
                ['denomination' => 10, 'year' => 2000, 'material' => 'Copper-Nickel', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/us dollar/10cents_dime_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/10cents_dime_back.jpg', 'description' => 'Ten cent coin (dime).', 'type' => 'Coin'],
                ['denomination' => 25, 'year' => 2000, 'material' => 'Copper-Nickel', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/us dollar/25cents_quarter_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/25cents_quarter_back.jpg', 'description' => 'Twenty-five cent coin (quarter).', 'type' => 'Coin'],
                ['denomination' => 50, 'year' => 2000, 'material' => 'Copper-Nickel', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/us dollar/50cents_halfdollar_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/50cents_halfdollar_back.jpg', 'description' => 'Fifty cent coin (half dollar).', 'type' => 'Coin'],
                ['denomination' => 1, 'year' => 2000, 'material' => 'Copper-Nickel Clad', 'is_active' => true, 'issue_date' => '2000-01-01', 'front_image_path' => 'img/Currencies/us dollar/1dollar_coin_front.jpg', 'back_image_path' => 'img/Currencies/us dollar/1dollar_coin_back.jpg', 'description' => 'One dollar coin.', 'type' => 'Coin'],
            ]);
        }
    }
}
